print("hello word")
a=5
b=6
sum=a+b
print(a+b)
num=int(input("enter a number"))
if num %2==0:
   print("even number")
else:
    print("odd number")      
year=int(input("enter a year:"))
if(year % 400==0)
    print("leap year")
else
    print("not a leap year")
PI=3.14159
print("value of PI is",pi)
pi=3.14
print("constant value=",pi)
num=int(input("enter a number:"))
square=num*num
print("squre:",square)
r=float(input("enter radius :"))
pi=3.14
area=pi*r*r
print("area of circle :")area
x=input("enter anything")
print("data types : ",type(x))
num=float(input("enter number :   "))
print("square root=",math.sqart(num))
print("absolute value: ",abs(num))

    