f1=open("file.txt","r")
data1 = f1.read()
f1.close()
f2=open("file2.txt","r")
data2 = f2.read()
f2.close()

merged=open("merge.txt","w")
merged.write(data1)
merged.write("\n")
merged.write(data2)
merged.close()
print("files merged into merged.txt")
